### ISSUE TITLE
Add footer in page hook?

### ISSUE THREAD

**Issue by winniehell** [dtolb/gitbook-plugin-custom-footer#1]
@dtolb Thank you for this plugin! :+1: 

Is there a reason why you append the footer in the `finish` hook rather than modifying the content in the `page` hook as in this example: https://toolchain.gitbook.com/plugins/hooks.html#example-to-replace-some-html ?

**Comment by dtolb** [comment]
@winniehell No particular reason, was mainly following along with the [gitbook-plugin-layout](https://www.npmjs.com/package/gitbook-plugin-layout) but for only the footer.

I couldn't get their plugin to work exactly how I needed so I got this one going.

**Comment by winniehell** [comment]
Thanks for explaining! :smiley: 

I'm closing this as I'm not sure if it is worth the effort to change it. Feel free to reopen if you disagree.

**Comment by dtolb** [comment]
I suppose that if there were other plugins that modified the HTML on the `finish` step they could cause some craziness in the footer used.

Feel free to try it out and submit a PR. If it works for both you and I; I'll merge-er-in and bump the version.
